export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";


export const GET_EXCHANGE_BEGIN = "GET_EXCHANGE_BEGIN";
export const GET_EXCHANGE = "GET_EXCHANGE";
export const GET_EXCHANGE_FAILURE = "GET_EXCHANGE_FAILURE";


export const EDIT_REQUEST = "LOGOUT_REQUEST";

export const ADD_REQUEST = "ADD_REQUEST";